=== Oliliana/Base_De_Datos_Avanzada/Ejemplo.dtd
<!ELEMENT Tienda (Productos)>
<!ELEMENT Productos (Producto+)>
<!ELEMENT Producto (ID, Articulo, Precio, Existencias)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Articulo (#PCDATA)>
<!ELEMENT Precio (#PCDATA)> 
<!ELEMENT Existencias (#PCDATA)>

=== Oliliana/Base_De_Datos_Avanzada/Ejemplo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Tienda SYSTEM "Ejemplo.dtd">
<!-- Olga Liliana Ruvalcaba Mata -->

<Tienda>
  <Productos>
    <Producto>
      <ID>L001</ID>
      <Articulo>Leche</Articulo>
      <Precio>30.50</Precio>
      <Existencias>30</Existencias>
    </Producto>

    <Producto>
      <ID>H101</ID>
      <Articulo>Huevo</Articulo>
      <Precio>27.80</Precio>
      <Existencias>15</Existencias>
    </Producto>

    <Producto>
      <ID>Q201</ID>
      <Articulo>Queso</Articulo>
      <Precio>40.70</Precio>
      <Existencias>50</Existencias>
    </Producto>

      <Producto>
      <ID>M301</ID>
      <Articulo>Mantequilla</Articulo>
      <Precio>15.99</Precio>
      <Existencias>35</Existencias>
    </Producto>
  </Productos>
</Tienda>
