=== Oliliana/Base_De_Datos_Avanzada/Práctica 2: DTD y XSD/Universidad.dtd
<!ELEMENT Universidad (UNI, alumnos)>
<!ELEMENT UNI (#PCDATA)>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (ID_A, Nombre, Carrera, materias)>

<!ELEMENT materias (materia+)>
<!ELEMENT materia (nombre, Calificación)>

<!ELEMENT ID_A (#PCDATA)>
<!ELEMENT Nombre (#PCDATA)>
<!ELEMENT Carrera (#PCDATA)>
<!ELEMENT Materia (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT Calificación (#PCDATA)>

=== Oliliana/Base_De_Datos_Avanzada/Universidad.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Universidad SYSTEM "Universidad.dtd">
<!-- Olga Liliana Ruvalcaba Mata -->

<Universidad>
  <UNI>UVM</UNI>

  <alumnos>
    <alumno>
      <ID_A>1</ID_A>
      <Nombre>Leila Perez</Nombre>
      <Carrera>Diseño de Modas</Carrera>
      <materias>
        <materia>
          <nombre>Patronaje</nombre>
          <Calificación>9.1</Calificación>
        </materia>
        <materia>
          <nombre>Confección</nombre>
          <Calificación>8.5</Calificación>
        </materia>
      </materias>
    </alumno>

    <alumno>
      <ID_A>2</ID_A>
      <Nombre>Mateo Rodriguez</Nombre>
      <Carrera>Ingeniería en Mecatrónica</Carrera>
      <materias>
        <materia>
          <nombre>Electronica</nombre>
          <Calificación>9.0</Calificación>
        </materia>
        <materia>
          <nombre>Control Numérico</nombre>
          <Calificación>8.8</Calificación>
        </materia>
      </materias>
    </alumno>

    <alumno>
      <ID_A>3</ID_A>
      <Nombre>Valentina Diaz</Nombre>
      <Carrera>Ingenieria Civil</Carrera>
      <materias>
        <materia>
          <nombre>Estructuras</nombre>
          <Calificación>9.2</Calificación>
        </materia>
        <materia>
          <nombre>Resistencia de Materiales</nombre>
          <Calificación>8.9</Calificación>
        </materia>
      </materias>
    </alumno>

    <alumno>
      <ID_A>4</ID_A>
      <Nombre>Valeria Vazquez</Nombre>
      <Carrera>Arquitectura</Carrera>
      <materias>
        <materia>
          <nombre>Dibujo Arquitectonico</nombre>
          <Calificación>9.3</Calificación>
        </materia>
        <materia>
          <nombre>Diseño de Interiores</nombre>
          <Calificación>9.7</Calificación>
        </materia>
      </materias>
    </alumno>

    <alumno>
      <ID_A>5</ID_A>
      <Nombre>Diego Mora</Nombre>
      <Carrera>Ingenieria en Sistemas Computacionales</Carrera>
      <materias>
        <materia>
          <nombre>Sistemas Operativos</nombre>
          <Calificación>9.1</Calificación>
        </materia>
        <materia>
          <nombre>Base de Datos</nombre>
          <Calificación>9.0</Calificación>
        </materia>
      </materias>
    </alumno>
  </alumnos>
</Universidad>
